#!/bin/bash

ARCHIVE_NAME="$1"
REPO_ID="$2"
TOTAL_SIZE_MB="$3"
PART_COUNT="$4"
PASSWORD="$5"

cat > release_notes.md << EOF
## 📦 Repository Archive

- **Repository**: ${REPO_ID}
- **Total Size**: ${TOTAL_SIZE_MB} MB
- **Parts**: ${PART_COUNT} parts (45MB each)
- **Password Protected**: YES

### 🔐 Password
\`\`\`
${PASSWORD}
\`\`\`

### 📥 Download
Download **all** ZIP parts from the Assets section below, then extract using the password above.

### 🔧 Extraction Instructions
1. Download all files: \`${ARCHIVE_NAME}.zip\`, \`${ARCHIVE_NAME}.z01\`, etc.
2. Place them in the same folder
3. Extract \`${ARCHIVE_NAME}.zip\` with any zip tool (7-Zip, WinRAR, etc.)
4. Enter the password when prompted

---
*Generated by GitHub Actions on $(date '+%Y-%m-%d %H:%M:%S UTC')*
EOF

echo "Release notes created: release_notes.md"
